Issue-15: Add support for Maybe#filter(Predicate)
jlmorgan/java-functional-extras pull request #16
Opened 2019-09-07 19:55 UTC by jlmorgan

closes #15
SemVer:Minor
enhancement

2019-09-07 20:14 UTC, doomchild requested changes
Grammatical change.

2019-09-07 20:14 UTC, doomchild commented on docs/data/Maybe/Maybe.md
> +Instance methods that accept and argument have curried implementations provided by the `Maybes` class where the instance is always the last argument.
`accept and argument` → `accept an argument`

2019-09-07 20:25 UTC, jlmorgan commented on docs/data/Maybe/Maybe.md
> +Instance methods that accept and argument have curried implementations provided by the `Maybes` class where the instance is always the last argument.
Fixed.

2019-09-07 20:26 UTC, doomchild approved these changes
Seems legit.

2019-09-09 15:18 UTC, doomchild approved these changes
Seems legit.

2019-09-11 11:55 UTC, merged